arrows:
    enabled: true
    exempt-worlds: []
    modifiers:
        head: 3
        neck: 4
        torso: 2
        crotch: 10
        legs: 0.8
        toes: 3
        unknown: 1
    effects: true
blocks:
    enabled: true
    exempt-worlds: []
    types:
        speed-up:
            enabled: true
            material: '35:1'
            velocity: 1.0
        slow-down:
            enabled: true
            material: '35:13'
            velocity: 1.0
        bounce:
           enabled: true
           material: '35:3'
           velocity: 1.0
    effects: true
blood:
    enabled: true
    exempt-worlds: []
    modifiers:
        players-color: red
        mobs-color: green
        animals-color: red
boats:
    enabled: true
    exempt-worlds: []
    damage-multiplyer: 1.0
    effects: true
heads:
    enabled: true
    chance: 1.0
minecarts:
    enabled: true
    exempt-worlds: []
    min-detected-speed: 0.01
    modifiers:
        players:
            damage: 1.5
            knockback: true
        mobs:
            damage: 2
            knockback: true
        animals:
            damage: 1.3
            knockback: true
    death-message: "&e<PLAYER> was killed by a speeding minecart"
    effects: true
pistons:
    enabled: true
    exempt-worlds: []
    sign-controlled: false
    weight:
        enabled: true
        modifier: 1.0
    power:
        entities: 4.0
        blocks: 3.0
    effects: true
player:
    enabled: true
    exempt-worlds: []
    modifiers:
        rates:
            hunger: 1.0
            experience: 1.0
        damage:
            pvp: 1.0
            pve: 1.0
            fire: 1.0
            suffocation: 1.0
            starvation: 1.0
            poison: 1.0
            fall: 1.0
            explosion: 1.0
weight:
    enabled: true
    exempt-worlds: []
    speed-modifier: 1.0
    default-speed: 1.0
    exempt-creative: true
    recalculate-when-walking: false
misc:
    debug: false
    movement-fix: true
    prefix: "[MorePhysics]"
