arrows:
    enabled: true
    modifiers:
        head: 3
        neck: 4
        torso: 2
        crotch: 10
        legs: 0.8
        toes: 3
        unknown: 1
    effects: true
blood:
    enabled: true
    modifiers:
        players-color: red
        mobs-color: green
        animals-color: red
boats:
    enabled: true
    damage-multiplyer: 1.0
    effects: true
minecarts:
    enabled: true
    min-detected-speed: 0.01
    modifiers:
        players:
            damage: 1.5
            knockback: true
        mobs:
            damage: 2
            knockback: true
        animals:
            damage: 1.3
            knockback: true
    death-message: "&e<PLAYER> was killed by a speeding minecart"
    effects: true
pistons:
    enabled: true
    calculate-player-weight: true
    power:
        entities: 4.0
        blocks: 3.0
    effects: true
player:
    enabled: true
    modifiers:
        rates:
            hunger: 1.0
            experience: 1.0
        damage:
            pvp: 1.0
            pve: 1.0
            fire: 1.0
            suffocation: 1.0
            starvation: 1.0
            poison: 1.0
            fall: 1.0
            explosion: 1.0
weight:
    enabled: true
    speed-modifier: 0.0001
    exempt-creative: true
misc:
    debug: false
    log-prefix: "[MorePhysics]"
