pistons:
    enabled: true
    exempt-worlds: []
    sign-controlled: false
    cancel-fall-damage: false;
    weight:
        enabled: true
        modifier: 1.0
    power:
        entities: 1.0
        blocks: 1.0
    pushed-blocks:
    - 12
    - 13
    pushed-blocks-blacklist: false
    effects: true
weight:
    enabled: true
    exempt-worlds: []
    only-process-armor: false
    speed-modifier: 1.0
    default-speed: 1.0
    exempt-creative: true
    recalculate-when-walking: false
misc:
    debug: false
    movement-fix: true
    prefix: "[MorePhysics]"
