pistons:
    enabled: true
    exempt-worlds: []
    sign-controlled: false
    weight:
        enabled: true
        modifier: 1.0
    power:
        entities: 4.0
        blocks: 3.0
    effects: true
weight:
    enabled: true
    exempt-worlds: []
    speed-modifier: 1.0
    default-speed: 1.0
    exempt-creative: true
    recalculate-when-walking: false
misc:
    debug: false
    movement-fix: true
    prefix: "[MorePhysics]"
