arrows:
    enabled: true
    exempt-worlds: []
    modifiers:
        head:
            damage: 2.5
            damage-range: 0.5
            effects: []
        neck:
            damage: 3.0
            damage-range: 0.5
            effects: []
        torso:
            damage: 1.0
            damage-range: 0.0
            effects: []
        crotch:
            damage: 4.0
            damage-range: 0.5
            effects: []
        legs:
            damage: 1.5
            damage-range: 0.5
            effects: []
        toes:
            damage: 2.0
            damage-range: 0.5
            effects: []
        unknown:
            damage: 1.0
            damage-range: 0.0
            effects: []
    players-only: false
    effects: true
blocks:
    enabled: true
    exempt-worlds: []
    affect-vehicles: true
    cancel-fall-damage: false
    types:
        speed-up:
            enabled: true
            material: '35:1'
            velocity: 1.0
        slow-down:
            enabled: true
            material: '35:13'
            velocity: 1.0
        bounce:
           enabled: true
           material: '35:3'
           velocity: 1.0
    effects: true
blood:
    enabled: true
    exempt-worlds: []
    types:
        players:
            enabled: true
            color: red
        mobs:
            enabled: true
            color: green
        animals:
            enabled: true
            color: red_alt
boats:
    enabled: true
    exempt-worlds: []
    damage-multiplyer: 1.0
    effects: true
minecarts:
    enabled: true
    exempt-worlds: []
    min-detected-speed: 0.01
    modifiers:
        players:
            damage: 1.5
            knockback: true
        mobs:
            damage: 2
            knockback: true
        animals:
            damage: 1.3
            knockback: true
    death-message: "&e<PLAYER> was killed by a speeding minecart"
    effects: true
pistons:
    enabled: true
    exempt-worlds: []
    sign-controlled: false
    cancel-fall-damage: false;
    weight:
        enabled: true
        modifier: 1.0
    power:
        entities: 1.0
        blocks: 1.0
    pushed-blocks:
    - 12
    - 13
    pushed-blocks-blacklist: false
    effects: true
player:
    enabled: true
    exempt-worlds: []
    modifiers:
        rates:
            hunger: 1.0
            experience: 1.0
        damage:
            pvp: 1.0
            pve: 1.0
            fire: 1.0
            suffocation: 1.0
            starvation: 1.0
            poison: 1.0
            fall: 1.0
            explosion: 1.0
weight:
    enabled: true
    exempt-worlds: []
    only-process-armor: false
    speed-modifier: 1.0
    default-speed: 1.0
    exempt-creative: true
    recalculate-when-walking: false
misc:
    debug: false
    movement-fix: true
    prefix: "[MorePhysics]"
updater:
    enabled: true
    channel: recommended
