name: MorePhysics
main: com.wolvencraft.morephysics.MorePhysics
website: http://dev.bukkit.org/bukkit-plugins/morephysics/
version: 2.4.0
authors: [FriedTaco, bitWolfy]
permissions:
    morephysics.exempt:
        description: Exempts the player from the effects of MorePhysics
        default: false