name: MorePhysics
main: com.shackledmc.physics.Physics
website: http://dev.bukkit.org/bukkit-plugins/physics/
version: 2.3.0
authors: [FriedTaco, bitWolfy]
permissions:
    physics.*:
        description: Applies the effects of MorePhysics to players
        default: false
        children:
            physics.arrows: true
            physics.blood: true
            physics.boats: true
            physics.minecarts: true
            physics.pistons: true
            physics.weight: true
    physics.arrows:
        description: Enables body part-specific critical damage
        default: false
    physics.blood:
        description: Enables blood particle effects
        default: false
    physics.boats:
        description: Enables boats sinking when receiving damage
        default: false
    physics.minecarts:
        description: Enables damage dealt by moving minecarts
        default: false
    physics.pistons:
        description: Enables launchy pistons
        default: false
    physics.player:
        description: Enables player rate modifications
        default: false
    physics.weight:
        description: Enables inventory weight
        default: false
          